version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                name: Install packages
                command: yarn
  
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                name: Tests Validate
                command: yarn test

  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                name: Lint Validate
                command: yarn lint
  
  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Authenticate to npm
                command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
            - run: 
                name: Publish package
                command: npm publish

workflows:
    validation:
      jobs:
        - install
        - test
        - lint
    publish:
      jobs:
        - publish:
            filters:
              branches:
                only: master